on:
  push:
    branches:
    - main
    - 'develop/**'

env:
  VERSION: '0.0.1'

jobs:
  my_job:
    runs-on: self-hosted   
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
      
    - name: Show Docker Version
      run: docker --version

    - name: Show Version
      run: echo ${VERSION}

    - name: compile App with docker to hotel/compiled image
      run: docker build -t hotel/compiled -f Dockerfiles/DockerfileCompile .

    - name: sonarQubeScanner
      run: |
       docker container rm hotelCompiled || true
       docker create --name hotelCompiled  hotel/compiled
       docker cp hotelCompiled:app/build/ ./build
       docker run \
       --rm \
       -e SONAR_HOST_URL="${{ vars.URL }}" \
       -e SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}" \
       -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=${{ vars.KEY }} -Dsonar.sources=src/main -Dsonar.java.libraries=build/libs -Dsonar.java.binaries=build/classes -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml -Dsonar.junit.reportsPath=build/test-results" \
       -v "${PWD}:/usr/src" \
       sonarsource/sonar-scanner-cli

    - name: pandocFile
      run: |
        docker run --rm \
        --volume "$(pwd):/data" \
        --user $(id -u):$(id -g) \
        pandoc/latex docs/README.md -o "documentation.pdf" --pdf-engine=xelatex \
        --standalone --toc --toc-depth=2 --highlight-style=tango

    - name: build Mkdocs html
      run: docker run --rm -v "${PWD}:/docs" -u $(id -u):$(id -g) squidfunk/mkdocs-material build

    - name: nginx
      run: docker build -t hoteldoc -f Dockerfiles/DockerfileNGINX .

    - name: Create Runnable Dockerimage for Hotel
      run: docker build -t hotel -f Dockerfiles/DockerfileRunnable .

    - name: Tag the Docker image
      run: |
        docker image tag hotel 10.0.40.162:5000/team6/hotel:${{ env.VERSION }}
        docker image tag hoteldoc 10.0.40.162:5000/team6/hoteldoc:${{ env.VERSION }}

    - name: Push to Registry
      run: |
        docker image push 10.0.40.162:5000/team6/hotel:${{ env.VERSION }}
        docker image push 10.0.40.162:5000/team6/hoteldoc:${{ env.VERSION }}

    - name: Create SSH Key
      run: |
        printf "%s" "${{ secrets.PROD_SERVER_SSH_KEY }}" > ${{ github.workspace }}/id_rsa
        chmod 600 ${{ github.workspace }}/id_rsa

    - name: Deploy on production server
      run: |
        ssh -i ${{ github.workspace }}/id_rsa -o StrictHostKeyChecking=no team6@10.0.40.163 '
          docker pull 10.0.40.162:5000/team6/hotel:${{ env.VERSION }}
          docker container stop hotel || true
          docker container rm hotel || true
          docker run --name hotel -d -p 16000:8082 10.0.40.162:5000/team6/hotel:${{ env.VERSION }}
          
          docker pull 10.0.40.162:5000/team6/hoteldoc:${{ env.VERSION }}
          docker container stop hoteldoc || true
          docker container rm hoteldoc || true
          docker run --name hoteldoc -d -p 16001:80 10.0.40.162:5000/team6/hoteldoc:${{ env.VERSION }}
        '

    - name: Cleanup Docker image
      run: |
       docker container rm hotelCompiled || true
       docker image rm hotel/compiled || true
       docker container prune -f
       docker image prune -af
       rm ${{ github.workspace }}/id_rsa
        

      

