on:
  push:
    branches:
    - main
    - 'develop/**'
jobs:
  my_job:
    runs-on: self-hosted   
    steps:
    - uses: actions/checkout@v4
    - name: Check contents
      run: ls -al
    - name: Test
      run: |
        cd docker-demo
        docker build -t sampleapp:v1 .
    - name: TestIndex
      run: |
        docker run -p 8080:80 sampleapp:v1
    - name: Verify Container is Running
      run: |
          docker ps
          docker logs sampleapp_container
    - name: Clean Up
      run: |
          docker stop sampleapp_container
          docker rm sampleapp_container